# Generated by Django 2.2.24 on 2022-02-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stuff',
            new_name='item',
        ),
    ]
